<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BooksTypes', 'doctrine');

/**
 * BaseBooksTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $booktype
 * 
 * @method string     getBooktype() Returns the current record's "booktype" value
 * @method BooksTypes setBooktype() Sets the current record's "booktype" value
 * @property  $
 * 
 * @package    lostbook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBooksTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bookstypes');
        $this->hasColumn('booktype', 'string', 10, array(
             'type' => 'string',
             'primary' => true,
             'length' => 10,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('books', array(
             'local' => 'booktype',
             'foreign' => 'status'));
    }
}