<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PeopleBook', 'doctrine');

/**
 * BasePeopleBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $people_id
 * @property integer $book_id
 * @property People $People
 * @property Book $Book
 * 
 * @method integer    getId()        Returns the current record's "id" value
 * @method integer    getPeopleId()  Returns the current record's "people_id" value
 * @method integer    getBookId()    Returns the current record's "book_id" value
 * @method People     getPeople()    Returns the current record's "People" value
 * @method Book       getBook()      Returns the current record's "Book" value
 * @method PeopleBook setId()        Sets the current record's "id" value
 * @method PeopleBook setPeopleId()  Sets the current record's "people_id" value
 * @method PeopleBook setBookId()    Sets the current record's "book_id" value
 * @method PeopleBook setPeople()    Sets the current record's "People" value
 * @method PeopleBook setBook()      Sets the current record's "Book" value
 * 
 * @package    lostbook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePeopleBook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('people_book');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('people_id', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('book_id', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('People', array(
             'local' => 'people_id',
             'foreign' => 'id'));

        $this->hasOne('Book', array(
             'local' => 'book_id',
             'foreign' => 'id'));
    }
}