<?php

/**
 * BooksTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BooksTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BooksTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BooksTypes');
    }
}