<?php

/**
 * BooksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BooksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BooksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Books');
    }
}