<?php

/**
 * PeopleBookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeopleBookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeopleBookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PeopleBook');
    }
}