<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('books', array(
             'id' => 
             array(
              'type' => 'int',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '',
             ),
             'author' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '150',
             ),
             'status' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '10',
             ),
             'person_id' => 
             array(
              'type' => 'int',
              'notnull' => '1',
              'length' => '',
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('person', array(
             'id' => 
             array(
              'type' => 'int',
              'primary' => '1',
              'length' => '',
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => '10',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'group' => 
             array(
              'type' => 'int',
              'length' => '',
             ),
             'adress' => 
             array(
              'type' => 'string',
              'length' => '300',
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('books');
        $this->dropTable('person');
    }
}