<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('books', 'books_people_id_person_id', array(
             'name' => 'books_people_id_person_id',
             'local' => 'people_id',
             'foreign' => 'id',
             'foreignTable' => 'person',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('books', 'books_people_id', array(
             'fields' => 
             array(
              0 => 'people_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('books', 'books_people_id_person_id');
        $this->removeIndex('books', 'books_people_id', array(
             'fields' => 
             array(
              0 => 'people_id',
             ),
             ));
    }
}