options:
  collate: utf8_unicode_ci
  charset: utf8

Books:
  connection: doctrine
  tableName: books
  columns:
    id:
      type: int
      primary: true
      autoincrement: true
    author:
      type: string(150)
    name:
      type: string(150)
      notnull: true
    status:
      type: string(10)
      notnull: true
    person_id:
      type: int
      notnull: true
    code:
      type: string(10)
  relations:
    Person:
      local: people_id
      foreign: id
      onDelete: CASCADE
Person:
  connection: doctrine
  tableName: person
  columns:
    id:
      type: int
      notnull: true
      primary: true
    code:
      type: string(10)
    name:
      type: string(100)	
    group:
      type: int
    adress:
      type: string(100)
    email:
      type: string(100)
      notnull: true
