options:
  collate: utf8_unicode_ci
  charset: utf8

Book:
  connection: doctrine
  tableName: book
  columns:
    id:
      type: integer(11)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(250)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    code:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    PeopleBook:
      local: id
      foreign: people_id
      type: one
      
People:
  connection: doctrine
  tableName: people
  columns:
    id:
      type: integer(11)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(250)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(250)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    PeopleBook:
      local: id
      foreign: book_id
      type: one
      
PeopleBook:
  connection: doctrine
  tableName: people_book
  columns:
    id:
      type: integer(11)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    people_id:
      type: integer(11)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    book_id:
      type: integer(11)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    People:
      local: people_id
      foreign: id
      type: one
    Book:
      local: book_id
      foreign: id
      type: one
      